DROP SCHEMA IF EXISTS RESTAURANT;
CREATE SCHEMA RESTAURANT;
USE RESTAURANT;
CREATE TABLE FOOD(
  ID INT PRIMARY KEY,-- 4 số 
  FNAME VARCHAR(100),
  PRICE BIGINT,
  INGREDIENTS TEXT
);
ALTER TABLE FOOD 
ADD STOCK_QUANTITY INT;
ALTER TABLE FOOD
ADD IMAGE_URL VARCHAR(255);
CREATE TABLE CLERK (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(50),
  CNAME varchar(50),
  PHONE VARCHAR(10),
  CMND VARCHAR(10),
  BIRTHDATE DATE,
  PWD TEXT,
  IMG_URL VARCHAR(255)
);
CREATE TABLE CHEF (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(50),
  CNAME varchar(50),
  PHONE VARCHAR(10),
  CMND VARCHAR(10),
  BIRTHDATE DATE,
  PWD TEXT,
  IMG_URL VARCHAR(255)
);

CREATE TABLE FOOD_CATEGORY(
  FID INT,
  CATEGORY VARCHAR(100),
  PRIMARY KEY(FID, CATEGORY),
  FOREIGN KEY (FID) REFERENCES FOOD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE FOOD_KEYWORD(
  FID INT,
  KEYWORD VARCHAR(100),
  PRIMARY KEY(FID, KEYWORD),
  FOREIGN KEY (FID) REFERENCES FOOD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);